### PR TITLE
Moves links on homepage, so they are not obstructed by long host names

### LINKED ISSUE #63: Long domain names are problematic for the homepage
The "Home" and "Signup" links are hard to see

Yes, my domain name is longer than many, but I don't think it unreasonable:
image

### PR DESCRIPTION
**Pull request by DougReeder**
Closes #63

### CODE REVIEW

**Comment by JakubNer** [comment]
This PR has the previous Apache RP commit and the CSS commit. 

Do you want to separate them into branches off of same base master commit or delete the other PR?

**Comment by raucao** [comment]
Maybe helpful: `git cherry-pick` is your friend! :)

**Comment by DougReeder** [comment]
I've removed the extraneous commit.  (I presumed the other PR would get reviewed first.)

**Review by raucao — APPROVED** [review]
:+1:

**Pull request merged**
