### PR TITLE
Change default config file to conf.json

### PR DESCRIPTION
**Pull request by stokito**
It's generally a good practice to have file extensions to make it easier for users.

Also it would be great to just have the file as a config by default.

### CODE REVIEW

**Review by DougReeder — COMMENTED** [review]
This seems reasonable to me.

**Comment by raucao** [comment]
+1

**Review by DougReeder — APPROVED** [review]

**Comment by stokito** [comment]
@raucao can you please merge it? Like others PRs are in fact ready to be merged

**Comment by raucao** [comment]
I am not an official maintainer of this repository/project.

@DougReeder Is there a specific reason why you approved without merging?

**Pull request merged**
