### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by DougReeder**
Four years is way too long to not update a package in NPM!

### CODE REVIEW

**Comment by raucao** [comment]
Did you use `npm version` for this? Release version changes should create signed Git tags with the new version number.

**Comment by DougReeder** [comment]
I believe `npm version` also publishes to NPM (without running any checks)

**Comment by DougReeder** [comment]
> I believe `npm version` also publishes to NPM (without running any checks)

Ah, no, I misremembered - there's an explicit `npm publish`.  Will update this.

**Comment by raucao** [comment]
See https://docs.npmjs.com/cli/v7/commands/npm-version#description for enabling tag signing.

**Comment by raucao** [comment]
I just installed https://github.com/release-drafter/release-drafter for this repo, and will open a PR for its config file.

I would propose to remove the tag again, merge that PR, then tag the new version. This way, we will get an automatic draft for the release notes, created from all closed PRs and linked to those as well. It will make publishing release notes so much easier.

**Comment by raucao** [comment]
Alternatively, we could merge this first and then merge the release drafter config, in which case we may just have to wait for the next PR to be closed until we get the draft created. @DougReeder Let me know what you prefer.

**Comment by DougReeder** [comment]
I've removed the tag. Let me know if you want me to re-add it.

**Comment by raucao** [comment]
I manually tagged the last commit and pushed it to master.

**Comment by raucao** [comment]
@DougReeder I have edited the release notes and removed the entries from before 0.1.5 was published. Feel free to edit and publish as you see fit:

https://github.com/remotestorage/armadietto/releases

**Comment by rosano** [comment]
Nice 🥳

**Pull request merged**
