### PR TITLE
Display all authenticated apps for a user on their account page

### PR DESCRIPTION
**Pull request by AngeloR**
I added a new "Account" link in the header that allows users to view
all the apps that they've approved on their armadietto server. It will
prompt them to log in with their username/password and then it will
display:
- Their account name (username@host)
- A table of all their approved apps, with info about what permissions
  it has requested

The link appears regardless of the signup option to allow the server
manager to view their data.

Screen Shot 2021-05-18 at 5 10 10 PM

Fixes: #44

### CODE REVIEW

**Comment by AngeloR** [comment]
Bumping on this

**Comment by raucao** [comment]
@silverbucket Had a chance to get back into the code yet?

**Comment by silverbucket** [comment]
I have been pretty busy with some other high priority work and have had to put a lot of stuff on hold the past few months. So I'm sorry to say, I still haven't had a chance to even start with this. I'll try to get to it as soon as I can, possibly this weekend- but no promises yet.

**Comment by raucao** [comment]
I had a look at this in a browser today (haven't reviewed any code yet).

There's one thing that immediately stood out to me: I was able to see the authorizations on the new account page, but there's no button to revoke any of them. I have not used Armadietto (or reStore) with real data before, so I don't really know what the feature set is. Is it possible that users are currently not able to revoke authorizations at all?

I also found a minor bug with the favicons: when it cannot find one, there's just a line of big text above the domain name.

There's also a small layout issue with the permissions column: when the category name is too long, the text breaks line and looks a bit awkward.

**Comment by AngeloR** [comment]
I wasn't sure what the PR/submission process was for such a large change. I'm definitely open to working on it because it's definitely functionality that should be present. 

I can update the issue with more information and take it from there.

**Comment by raucao** [comment]
I think there is currently no official process for PRs. It would be nice if one or two people could commit to being the official maintainers of this repo/server in order to manage pull requests as well as any other contributions. (I'm not that person. I merely saw PRs coming in over a longer timeframe, with no progress towards merging them. So I took the liberty of triaging a bit and trying to move things forward.)

/cc @lesion @thornjad

**Comment by raucao** [comment]
> I'm definitely open to working on it because it's definitely functionality that should be present.

I think if users can see the authorizations that exist, it's almost a required feature for an RS server that they can revoke the authorization on that screen as well. So yeah, I would propose to add that in the same PR if possible.

**Comment by raucao** [comment]
@AngeloR Hey there. Are you still planning to work on this PR? Seems to me like there's not that much to add for it to be ready to merge...

**Comment by stokito** [comment]
The PR is important and you can just merge it even if it's not ideal. Later others may send PRs with more features like revoking and big fixing.

**Pull request closed without merging**
