### PR TITLE
first pass at including logging via winston

### PR DESCRIPTION
**Pull request by AngeloR**
Opening this as a draft because I'm not sure if my implementation of the logging configuration is ideal.

This includes logging via [winston](https://github.com/winstonjs/winston), that's somewhat configurable via the configuration file. It introduces a new `logging` root property on the config object that supports the following:

```
  "logging": {
	  "log_dir": ".",
	  "log_files": ["error", "combined"]
  },

```

- `log_dir` should be an absolute path to the location of the logs. If you use something relative, it will be relative to wherever you start the server from. 
- `log_files` allows you to specify an array of files that match any of `emerg`, `alert`, `crit`, `error`, `warning`, `notice`, `info`, `debug`, or `combined`. When specified a specific log file is created that contains that particular level of error. `combined` is a special case that results in all log levels being written to a single log file. 

The logger is accessible from everywhere via `this._logger`. 

If you pass an `Error` object to the logger it will include a small stack trace for when the error was thrown.

```
this._logger.error(new Error('oh yes!'));
```

### CODE REVIEW

**Comment by raucao** [comment]
Just a quick question, without having looked into the details: how would I log to stdout, to use `systemd-journald` instead of custom log files on modern Linux systems?

**Comment by AngeloR** [comment]
@raucao What do you think of the new config option to also allow output to stdout? I haven't touched on tests or anything like that just because I want to get the interface down first.

**Comment by raucao** [comment]
Looks nice. (Haven't tested it yet.)

**Comment by pataquets** [comment]
Thanks for submitting the PR, @AngeloR.
IMHO, logging should be by default to `stdout` and without any timestamp. Most deployment and orchestration tools nowadays expect both (eg. Docker).

**Comment by AngeloR** [comment]
I agree @pataquets I think just having only stdout is a good default. I just also wanted to use this PR as a way to get some input from the core team on the configuration.

**Comment by raucao** [comment]
@AngeloR Are you still working on this, or should we close it? Currently triaging PRs in this repo...

**Comment by AngeloR** [comment]
I'll be continuing work on this in the next day or two! Thanks for following up.

**Comment by DougReeder** [comment]
Reviewers may also want to look at https://github.com/AngeloR/armadietto/pull/1 which preserves the existing behavior of logging to stdout when no logging is configured.

**Comment by DougReeder** [comment]
Closing this PR in favor of one from https://github.com/remotestorage/armadietto/tree/logging

**Pull request closed without merging**
