### PR TITLE
Adds logging via winston; default is logging to stdout

### LINKED ISSUE #48: Audit logs for server + access
In order to actually use this in production we should implement a proper logging system that 

- Differentiates between info/debug/error/warnings
- Has the ability to write log files to a user-defined location instead of just stdout
- Log HTTP requests (as informational, perhaps access.log)

I'm happy to tackle this change.

### PR DESCRIPTION
**Pull request by DougReeder**
I have set reasonable priorities for logging, and retained the existing messages for errors. Input on these matters is welcomed!

I have not changed the existing error handling, so some errors are logged separately from their requests.  Future work might refactor the error handling to consolidate these.

resolves #48

### CODE REVIEW

**Review by raucao — CHANGES_REQUESTED** [review]
I had a look at the branch just now and fixed a minor bug when using the default http host config. The logs look great to me!

However, I found a security issue with the default output: it will log access tokens in the request logs for the OAuth redirects (by way of logging the entire URL including fragments). Tokens should never be logged in my opinion, no matter the log level. If a server operator needs that information for some reason, and they think it's OK to keep it in their log files, then I think they should manually add logging for that themselves.

**Comment by DougReeder** [comment]
Thank you, I'd been wondering about that.

Unfortunately, I think I overwrote your changes by force-pushing without double-checking. Can you please re-add your changes?

**Comment by DougReeder** [comment]
I believe I've restored your fix, and prevented the token from being logged, but please check my work.

**Comment by raucao** [comment]
Could you *please* stop deleting history and force-pushing to the branch? It makes collaboration very difficult, and also deletes authorship information. Thank you!

**Comment by DougReeder** [comment]
My apologies. I won’t do it again.

**Review by raucao — APPROVED** [review]
Extra information is now stripped from the OAuth redirect logs. :+1: 

I think this is ready to merge, and can be improved and extended in future PRs.

**Pull request merged**
